controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diffdrive_controller:
      type: diff_drive_controller/DiffDriveController


joint_state_broadcaster:
  ros__parameters:
    joints: ["left_wheel_joint", "right_wheel_joint"]

diffdrive_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.233000 # 0.116500*2 from TurtleBot4.proto
    wheel_radius: 0.035750000000000004

    # The real separation between wheels is not resulting in a perfect odometry
    wheel_separation_multiplier: 1.06793648481

    use_stamped_vel: false
    base_frame_id: "base_link"
    
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 0.2 # Maximal speed of turtlebot
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 0.1